### ISSUE TITLE
cant compile,tryed many settings

### ISSUE THREAD

**Issue by ParalysisCode** [ldpreload/BlackLotus#11]
i had a lot of errors but after changing to X86 and changedlinker settings am getting linker errors like entrypoint and subsystem

you cant compile it just like that, can u please help us with the compiling issue?

after playing with settings my only error is
`nzt.obj : error LNK2019: unresolved external symbol _BookitInitialize referenced in function _BotInitialize`

**Comment by ParalysisCode** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _BookitInitialize	Bot	C:\Users\user\OneDrive\Desktop\src\Bot\nzt.obj	1

**Comment by ldpreload** [comment]
You need to have Windows Drivers Development Kit (WDK), as well as the proper EFI drivers in order to compile the EFI drivers needed for the installation.

**Comment by ParalysisCode** [comment]
thank you. proper EFI drivers? what drivers can u help me with that please?
