### ISSUE TITLE
Compiled Success but no connection

### ISSUE THREAD

**Issue by jerrydrow** [ldpreload/BlackLotus#18]
I just compiled with no error and code seems perfect.
but no connection anyone can help.

**Comment by wgetnz** [comment]
i have the same problem

**Comment by uwuw7** [comment]
same lol, just broken 💀

**Comment by ldpreload** [comment]
Inside of Shared/config.c, you can actually list multiple hosts for your C2. Make sure you've got the right host, IP address, or whatever your C2 needs.

```
#include <Windows.h>
#include "config.h"

LPTSTR      g_Hosts[]    = { "127.0.0.1", "10.0.0.65", NULL};
UCHAR      g_NumberHosts  = (UCHAR)(sizeof(g_Hosts) / sizeof(LPTSTR));
```

Please also make sure to import the SQL file located in private/db.sql to MySQL (or whichever SQL server you prefer).

Final result:
![photo](https://github.com/ldpreload/BlackLotus/assets/95562574/d641e21e-2539-4423-aaba-ccb5eec4df68)

**Comment by gabriel-maxx** [comment]
@worldlevelpen Do you have Telegram?

**Comment by unfairDude** [comment]
> I just compiled with no error and code seems perfect. but no connection anyone can help.

can you share with me the compiled version? i Cant get it working

**Comment by unfairDude** [comment]
> @worldlevelpen Do you have Telegram?

did u manage to compile it
