### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by LionHackerman** [ldpreload/BlackLotus#2]
When compiling on in Visual Studio 2022 on Windows 10 (Release/x64), I get this error:

![image](https://github.com/ldpreload/BlackLotus/assets/58070003/97677a82-2e0c-47ef-880d-85f766cc67df)

**Comment by hotline1337** [comment]
use intel compiler or llvm for x64 inline asm

**Comment by ldpreload** [comment]
You are compiling under the wrong architecture for your system.
