### ISSUE TITLE
Include Errors

### ISSUE THREAD

**Issue by ACDiamond** [ldpreload/BlackLotus#20]
Im getting weired include errors, that it cannot include the <Windows.h> for some reason in the "Shared\API" files.
I have a similar problem with NTSecAPI.h , TlHelp32.h, ShlObj.h, Wininet.h, stdio.h...
That makes absolutely no sense because those headers come with the Windows SDK which is installed and works for everything else. Would be nice if someone helps me

**Comment by changzhenxuan** [comment]
need help, too.

**Comment by C-fire** [comment]
> Im getting weired include errors, that it cannot include the <Windows.h> for some reason in the "Shared\API" files. I have a similar problem with NTSecAPI.h , TlHelp32.h, ShlObj.h, Wininet.h, stdio.h... That makes absolutely no sense because those headers come with the Windows SDK which is installed and works for everything else. Would be nice if someone helps me

which visual studio version are you using? The project was compiled with version 2019

**Comment by ling142857** [comment]
Shared projects are temporary files. Against the Bot and Encryptor projects change vcxitems to vcxproj, add the .user file, modify NzT.sln and reload.

**Comment by ling142857** [comment]
> 我收到奇怪的包含错误，由于某种原因它无法在“Shared\API”文件中包含 <Windows.h> 。 我对 NTSecAPI.h 、 TlHelp32.h 、 ShlObj.h 、 Wininet.h 、 stdio.h 也有类似的问题... 这完全没有意义，因为这些标头随 Windows SDK 一起安装并适用于其他所有内容。如果有人帮助我就好了

Shared projects are temporary files. Against the Bot and Encryptor projects change vcxitems to vcxproj, add the .user file, modify NzT.sln and reload.

**Comment by ling142857** [comment]
> Im getting weired include errors, that it cannot include the <Windows.h> for some reason in the "Shared\API" files. I have a similar problem with NTSecAPI.h , TlHelp32.h, ShlObj.h, Wininet.h, stdio.h... That makes absolutely no sense because those headers come with the Windows SDK which is installed and works for everything else. Would be nice if someone helps me

Shared projects are temporary files. Against the Bot and Encryptor projects change vcxitems to vcxproj, add the .user file, modify NzT.sln and reload.

**Comment by ldpreload** [comment]
> > Im getting weired include errors, that it cannot include the <Windows.h> for some reason in the "Shared\API" files. I have a similar problem with NTSecAPI.h , TlHelp32.h, ShlObj.h, Wininet.h, stdio.h... That makes absolutely no sense because those headers come with the Windows SDK which is installed and works for everything else. Would be nice if someone helps me
> 
> Shared projects are temporary files. Against the Bot and Encryptor projects change vcxitems to vcxproj, add the .user file, modify NzT.sln and reload.

Thank you for answering them.
