### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by gabriel-maxx** [ldpreload/BlackLotus#22]
Hello, I would like to know how do I compile the bootkit efi driver using edk2? there are no instructions in the project...

**Comment by unfairDude** [comment]
> Hello, I would like to know how do I compile the bootkit efi driver using edk2? there are no instructions in the project...

did u find out

**Comment by ldpreload** [comment]
> Hello, I would like to know how do I compile the bootkit efi driver using edk2? there are no instructions in the project...

Did you add it to VS?
You need to follow the instructions in the EDK2 documentation.
