### ISSUE TITLE
Can't compile, unresolved externals

### ISSUE THREAD

**Issue by uwuw7** [ldpreload/BlackLotus#6]
![image](https://github.com/ldpreload/BlackLotus/assets/52632945/e2fa3ab9-ed3a-411d-bb32-683b57dabfd3)

Tried using 2019, 2022, tried building with intel, wont even show me where the errors are

**Comment by uwuw7** [comment]
![image](https://github.com/ldpreload/BlackLotus/assets/52632945/7d1ece75-15a3-4664-896f-fe258ca66f65)

**Comment by ldpreload** [comment]
Looks like an error with your linker. Nothing to do with the code or project.

**Comment by uwuw7** [comment]
> Looks like an error with your linker. Nothing to do with the code or project.

Yeah I fixed it, but now theres a new issue
![image](https://github.com/ldpreload/BlackLotus/assets/52632945/a614cfdc-ae87-4fe5-9e96-a56c05fe66a5)

**Comment by uwuw7** [comment]
Tried building on x86, ARM, x64, ect

**Comment by ldpreload** [comment]
I'm not sure what you're doing in the WINNT header file, which is a system header file by the way. I still think it's an issue with your Linker / IDE.
